name: rabbitmq-server
base: core20
version: '3.10.7'
summary: AMQP server written in Erlang
description: |
  RabbitMQ is an implementation of AMQP, the emerging standard for
  high performance enterprise messaging. The RabbitMQ server is a
  robust and scalable implementation of an AMQP broker.
source-code: https://github.com/ML-PA-Consulting-GmbH/rabbitmq-server-snap
website: https://github.com/ML-PA-Consulting-GmbH/rabbitmq-server-snap
issues: https://github.com/ML-PA-Consulting-GmbH/rabbitmq-server-snap/issues
contact: https://github.com/ML-PA-Consulting-GmbH/rabbitmq-server-snap/issues
icon: assets/logo.png
license: Apache-2.0
architectures:
  - build-on: amd64
    run-on: arm64
# grade: devel
# confinement: devmode
grade: stable  
confinement: strict 

apps:
  rabbitmq-server:
    daemon: simple
    plugs:
      - network
      - network-bind
    restart-condition: on-failure
    restart-delay: 10s
    command: bin/rabbitmq-server
    stop-command: bin/rabbitmqctl stop

  rabbitmqctl:
    plugs:
      - network
      - network-bind
    command: bin/rabbitmqctl

  epmd:
    plugs:
      - network
      - network-bind
    command: usr/lib/erlang/bin/epmd

  rabbitmq-shell:
    plugs:
      - network
      - network-bind
    command: bin/bash

  rabbitmq-diagnostics:
    plugs:
      - network
      - network-bind
    command: bin/rabbitmq-diagnostics

parts:
  # debug:
  #   plugin: dump
  #   source: http://ftp.de.debian.org/debian/pool/main/s/strace/strace_4.26-0.2_arm64.deb
  #   source-type: deb

  assets:
    after: ["rabbitmq" ]
    plugin: dump
    source: assets
    stage:
      - etc/*
      - bin/*
      - "logo.png"

  rabbitmq:
    after: ["elixir" ]
    plugin: dump
    source: https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.10.7/rabbitmq-server_3.10.7-1_all.deb
    source-type: deb    
    source-checksum: sha1/026a50b240548c8216a674218856385d4c9c7d3f
    override-build: |
      snapcraftctl build
      sed -i 's|. ${RABBITMQ_CONF_ENV_FILE} \|\| true|. ${SNAP}${RABBITMQ_CONF_ENV_FILE} \|\| true|g' $SNAPCRAFT_PART_INSTALL/usr/lib/rabbitmq/bin/rabbitmq-env


  elixir:
    after: ["erlang" ]
    plugin: dump
    source: https://github.com/elixir-lang/elixir/releases/download/v1.13.3/Precompiled.zip
    source-type: zip
    source-checksum: sha1/7a2d0ff13beadcba3f566d692d960dcd785df5c8
    organize:
      '*': 'usr/'

  erlang:
    after: ["libgl1", "libglu", "libodbc", "libwxbase", "libltdl" ] # , "libgtk3u" is ignored to keep file size small, we won't need it anyways    
    plugin: dump
    source: https://packages.erlang-solutions.com/erlang/debian/pool/esl-erlang_25.0.2-1~ubuntu~focal_arm64.deb
    source-type: deb
    source-checksum: sha1/95922490ccab98804c6126faa6452256ff191852
    override-build: |
      snapcraftctl build
      sed -i 's|/usr/lib|$SNAP/usr/lib|g' $SNAPCRAFT_PART_INSTALL/usr/bin/erl
      sed -i 's|/usr/lib|$SNAP/usr/lib|g' $SNAPCRAFT_PART_INSTALL/usr/lib/erlang/bin/erl
    
  # ---------------------------
  # required runtime libraries:

  libgl1:
    after: ["libglx" ]
    plugin: dump
    source: http://ports.ubuntu.com/pool/main/libg/libglvnd/libgl1_1.3.1-1_arm64.deb
    source-type: deb
    source-checksum: sha1/56408a72863da278fcb038fd4e26e728362454aa

  libglx:
    after: ["libglvnd", "libx11" ]
    plugin: dump
    source: http://ports.ubuntu.com/pool/main/libg/libglvnd/libglx0_1.3.1-1_arm64.deb       
    source-type: deb
    source-checksum: sha1/de1bf7119a03fc394fd132f1a73e0ab249a7865b
      
  libglvnd:
    plugin: dump
    source: http://ports.ubuntu.com/pool/main/libg/libglvnd/libglvnd0_1.3.2-1~ubuntu0.20.04.2_arm64.deb
    source-type: deb
    source-checksum: sha1/9708c4d33d749dd9ad6d2376ef545c75f20ceef6
            
  libx11:
    after: ["libxcb" ]
    plugin: dump
    source: http://ports.ubuntu.com/pool/main/libx/libx11/libx11-6_1.6.9-2ubuntu1.2_arm64.deb
    source-type: deb
    source-checksum: sha1/0b97345a14b251665032d7a63846ded35e6f653f

  libxcb:    
    after: ["libxau", "libxdmcp" ]
    plugin: dump
    source: http://ports.ubuntu.com/pool/main/libx/libxcb/libxcb1_1.14-2_arm64.deb
    source-type: deb
    source-checksum: sha1/657a78eea9bb0bdf2a6735e48ef445a7749e123a

  libxau:    
    plugin: dump
    source: http://ports.ubuntu.com/pool/main/libx/libxau/libxau6_1.0.9-0ubuntu1_arm64.deb
    source-type: deb
    source-checksum: sha1/08039a2ba8dd54de607ec31668512e9b554d0e34

  libxdmcp:    
    plugin: dump
    source: http://ports.ubuntu.com/pool/main/libx/libxdmcp/libxdmcp6_1.1.3-0ubuntu1_arm64.deb
    source-type: deb
    source-checksum: sha1/6930f96ad599d440f5672b69c7ec9d3a607586c6

  libglu:    
    plugin: dump
    source: http://ports.ubuntu.com/pool/main/libg/libglu/libglu1-mesa_9.0.1-1build1_arm64.deb
    source-type: deb
    source-checksum: sha1/97a6378fa585d7b472f7bccd261a723766f52106

  libodbc:
    plugin: dump
    source: http://ports.ubuntu.com/pool/main/u/unixodbc/libodbc1_2.3.6-0.1build1_arm64.deb
    source-type: deb
    source-checksum: sha1/c708992b48e7c277f768694556eeccbd3c20aade

  libwxbase:
    plugin: dump
    source: http://ports.ubuntu.com/pool/universe/w/wxwidgets3.0/libwxbase3.0-0v5_3.0.4+dfsg-15build1_arm64.deb
    source-type: deb
    source-checksum: sha1/6c2a0a54bc6f32cc9bcc9b9709fa99173b837447

  libltdl:
    plugin: dump
    source: http://ports.ubuntu.com/pool/main/libt/libtool/libltdl7_2.4.6-14_arm64.deb
    source-type: deb
    source-checksum: sha1/81f10960d80ce8d125cf409a434bdc5355d0a53f

  # to keep the snap size small, we don't import libgtk3u, which itself needs a whole lot of other libraries
  # libgtk3u:
  #   plugin: dump
  #   source: http://archive.ubuntu.com/ubuntu/pool/universe/w/wxwidgets3.0/libwxgtk3.0-gtk3-0v5_3.0.4+dfsg-15build1_amd64.deb
  #   source-type: deb
  #   source-checksum: sha1/00359ac07798ac1315548569896c063d676594a2